### ISSUE TITLE
Simple Caching Implementation

### ISSUE THREAD

**Issue by aaguiarz** [openfga/roadmap#38]
Implement a per-node sub-problem cache. 

It should cache 'Check' results in-memory. This will speed up check queries that traverse the same paths more than once and check queries that are frequently used.

**Comment by aaguiarz** [comment]
Implement a per-node sub-problem cache. 

It should cache 'Check' results in-memory. This will speed up check queries that traverse the same paths more than once and check queries that are frequently used.

Needs to be optional, initially at the server-level, to preserve backwards compatibility.

**Comment by wcurrie** [comment]
This ticket is marked "Done" but did any cache get implemented (for OpenFGA)?

Would be great if the issue/PRs with the implementation were linked. From https://github.com/openfga/roadmap/issues/21 it seems like this is not Done.

**Comment by wcurrie** [comment]
Ah, https://github.com/openfga/roadmap/issues/21 is still open. Maybe this was just a duplicate.

**Comment by aaguiarz** [comment]
We split the task in two, one for a 'simple caching implementation' that has a cache-per-node, and another one that implies a distributed cache. This other one is open, this one is closed :)

**Comment by aaguiarz** [comment]
PR with the implementation https://github.com/openfga/openfga/pull/891
