### ISSUE TITLE
Additional Consistency Options for OpenFGA queries

### ISSUE THREAD

**Issue by aaguiarz** [openfga/roadmap#54]
In OpenFGA we currently support:

- Strong reads, if you don't configure the cache
- Eventually consistent reads, when you configure the cache 

We want to provide additional options to:

- Always request a strong consistent read
- Request for a consistent read if the cached data is staler than a specific timestamp/revision (or token, or zookie). This was moved to https://github.com/openfga/roadmap/issues/67

**Comment by rhamzeh** [comment]
This is now released in https://github.com/openfga/openfga/releases/tag/v1.6.0

The docs are here: https://openfga.dev/docs/interacting/consistency

Try it out, and let us know your feedback!
