### ISSUE TITLE
SQLite Storage Adapter

### ISSUE THREAD

**Issue by aaguiarz** [openfga/roadmap#56]
There are different use cases for which a SQLite storage adapter would be useful:

- Embedded/Mobile scenarios, where you want to bundle OpenFGA as a library + SQLite
- Deploying OpenFGA instances as a sidecar with static data in SQLite, or synchronized to a centralized OpenFGA instance using the /changes endpoint.
- If you are using SQLite as you main database and you don't want to operate a different one

We'd like to do https://github.com/openfga/roadmap/issues/57 before this one.

**Comment by golanglemonade** [comment]
Thanks @aaguiarz! Happy to help contribute here. We are using [turso](https://turso.tech/) for our main databases, and were interested in this to lessen the sprawl of our state machines. They maintain a fork of sqlite, `libsql` and they also have [golang clients](https://github.com/tursodatabase/go-libsql). We were also throwing around the idea of sidecar scenario you mentioned in the use cases. Let me know how I can help.

**Comment by rhamzeh** [comment]
This has been completed thanks to @DanCech 's contribution.

It will be released shortly in [v1.6.1](https://github.com/openfga/openfga/releases/tag/v1.6.1)
