### ISSUE TITLE
List Actions/Permissions

### ISSUE THREAD

**Issue by zachkirlew** [openfga/roadmap#62]
We are currently considering migrating to openfga but we were disappointed to see there's no openfga endpoint we can use to get all the allowed actions for a given user for a given resource. This is particularly useful information for the UI to conditionally render items. I've already looked into using the Read API to query relationships for a user and resource but [it doesn't take into consideration the authorisation model](https://openfga.dev/docs/interacting/relationship-queries#caveats-and-when-not-to-use-it-1).

The following systems provide this behaviour already:

- [List authorised action](https://www.osohq.com/docs/concepts/go-deeper/four-steps-to-authz/authz-enforcement-basics/checking-authorization-decisions#listing-authorized-actions) in OSO

- [Subject Permission List](https://docs.permify.co/api-reference/permission/subject-permission) in Permify

**Comment by rhamzeh** [comment]
Hi @zachkirlew , you can use the `ListRelations` method in any of our supported SDKs.

Try it out and let us know your feedback

**Comment by aaguiarz** [comment]
We added a new entry in the Roadmap to track the server side implementation 
https://github.com/openfga/roadmap/issues/69
