### ISSUE TITLE
API to retrieve all tuples for a user for a particular relationship and particular object type

### ISSUE THREAD

**Issue by aaguiarz** [openfga/roadmap#8]
In some scenarios like filtering or auditing, developers need to answer queries like "list all documents that user:X can read". 

Depending on the use case, the problem can be solved with the existing APIs, as described in our [Search with Permissions](https://openfga.dev/integration/advanced/search-with-permissions) documentation, but sometimes having a new API would be more practical.

The API would look like:

`Lookup(objectType, relation, user) --> List<ObjectID>`

**Comment by andreadistefano** [comment]
Hi, the link in your comment looks dead. I think it should point to this: [Search with Permissions](https://openfga.dev/docs/interacting/search-with-permissions)

**Comment by aaguiarz** [comment]
This work was completed, you can check the documentation for the ListObjects endpoint here https://openfga.dev/docs/interacting/relationship-queries
